version: "3.3"
services:

 facteur:
  build: .
  networks:
   - isolated_nw2
  restart: on-failure
  volumes:
   - /tmp
  container_name: factrice

networks:
 isolated_nw2:
  driver: bridge

volumes:
 db-data:
  driver: local